version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: evnict-table-tennis-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: table_tennis_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: evnict_user
      MYSQL_PASSWORD: evnict_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
